# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts7l gts7lwifi gts7xl gts7xlwifi r8q,$(TARGET_DEVICE)),)

endif
